---

- name: Get check-mk-livestatus
  get_url: url={{ check_mk_livestatus_url }} dest={{ download_dir }}/{{ mk_livestatus_src }}.tar.gz
  
- name: Unpack check-mk-livestatus source files
  shell: cd {{ download_dir }} && tar -xzvf {{ mk_livestatus_src }}.tar.gz creates={{ download_dir }}/{{ mk_livestatus_src }}

# Info: https://mathias-kettner.de/checkmk_livestatus.html
- name: Configure check-mk-livestatus
  shell: cd {{ download_dir }}/{{ mk_livestatus_src }} && ./configure --with-nagios4 creates={{ download_dir }}/{{ mk_livestatus_src }}/Makefile

- name: Make Install check-mk-livestatus
  shell: cd {{ download_dir }}/{{ mk_livestatus_src }} && make install creates=/usr/local/lib/mk-livestatus/livestatus.o
 
