---
# file: tasks/config_nagios.yml


- name: config_nagios | Configure localhost_thruk.cfg
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: 'root'
    group: 'root'
    mode: "0644"
  with_items:
    - { src: 'localhost_thruk.cfg.j2', dest: '{{ nagios_config_cfg_dir }}/localhost_thruk.cfg' }
  notify: Reload Nagios
