---
# file: tasks/main.yml 

- import_tasks: multi_os.yml
  tags:
    - config_nagios_thruk_cron
    - test_nagios_thruk

- name: main | Ensure download directory is present
  file:
    path: "{{ download_dir }}"
    state: directory

# Dependency gpg-agent required before running apt-key ansible module
- name: main | Install thruk dependencies
  package:
    name: "{{ thruk_dependencies | join(',') }}"
    state: present
  environment:
    DEBIAN_FRONTEND: noninteractive

- import_tasks: repositories.yml

- import_tasks: install_thruk.yml

- import_tasks: config_thruk.yml
  tags:
    - config_nagios_thruk

- import_tasks: config_nagios.yml

- import_tasks: config_thruk_logcache.yml

- import_tasks: config_thruk_cron.yml
  tags:
    - config_nagios_thruk_cron

- import_tasks: thruk_fixes.yml

- import_tasks: tests.yml
  tags:
    - test_nagios_thruk
