---
# file: tasks/tests.yml

# Es recomendado correr los handlers de cada rol antes de seguir con otro rol, sino los corre cuándo terminó de hacer todo
- name: tests | ensure handlers runs before continue
  meta: flush_handlers

- name: tests | ensure nagios is started
  service:
    name: "{{ nagios_service }}"
    state: started

- name: tests | test if "{{ nagios_live_sock }}" exist for thruk connection
  file:
    path: "{{ nagios_live_sock }}"
    state: file

- name: tests | ensure thruk is started
  service:
    name: "thruk"
    state: started
