---
- name: Converge
  hosts: all
  become: yes
  pre_tasks:
    - name: installing python-3 mysql libraries
      apt: name=python3-mysqldb state=present
      when: ansible_os_family == 'Debian'
  roles:
    - role: geerlingguy.mysql
    - role: ansible-role-nagios
    - role: coffeeitworks.ansible_nagios4_server_config
    - role: ansible_nagios4_server_thruk
